baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'My New Hugo Site'
theme = 'classless-blog'

[module]
[[module.mounts]]
source = 'static'
target = 'static'

[[module.mounts]]
source = 'attachments'
target = 'static/attachments'

[deployment]

[[deployment.targets]]
# An arbitrary name for this target.
name = "production"

# Amazon Web Services S3; see https://gocloud.dev/howto/blob/#s3
# For S3-compatible endpoints, see https://gocloud.dev/howto/blob/#s3-compatible
URL = "s3://yo.jv.run?region=us-east-1"