baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'My New Hugo Site'
theme = 'classless-blog'

[module]
[[module.mounts]]
source = 'static'
target = 'static'

[[module.mounts]]
source = 'attachments'
target = 'static/attachments'