baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'My New Hugo Site'
theme = 'classless-blog'

[module]
[[module.mounts]]
source = 'static'
target = 'static'

[[module.mounts]]
source = 'attachments'
target = 'static/attachments'

[deployment]

[[deployment.targets]]
name = "production"
URL = "s3://jvogt-websites?region=us-west-1/yo.jv.run"